{% set name = "robocorp" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/robocorp-{{ version }}.tar.gz
  sha256: 5409702cb0575990f16b6b613a09519125f437b4642cbb5b63e66f4f9dd3c7e7

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.9.0,<4.0.0
    - robocorp-tasks =2.4.2
    - robocorp-log =2.8.0
    - robocorp-workitems =1.4.1
    - robocorp-vault =1.3.0
    - robocorp-storage =1.0.2

test:
  imports:
    - robocorp
    - robocorp.tasks
    - robocorp.log
    - robocorp.workitems
    - robocorp.vault
    - robocorp.storage
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/robocorp/robo/
  summary: Robocorp core libraries for Python automation
  description: This is a metapackage for installing the core libraries of Robocorp Python automation framework. The following packages are currently included robocorp-tasks robocorp-log robocorp-workitems robocorp-vault robocorp-storage
  doc_url: https://robocorp.com/docs/python/robocorp
  doc_source_url: https://github.com/robocorp/robo/tree/master/docs
  dev_url: https://github.com/robocorp/robo#libraries
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - zaigner
