{% set name = "robocorp" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/robocorp-{{ version }}.tar.gz
  sha256: 2e8da9d5ce7122b73dea3a106a0e0c40147279e51382c2a3d818c46a55aaf20a

build:
  noarch: python
  script:
    - echo f | xcopy /f /y /S %RECIPE_DIR%\README.md %SRC_DIR%\README.md  # [win]
    - cp -R {{ RECIPE_DIR }}/README.md {{ SRC_DIR }}/README.md  # [unix]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - robocorp-tasks >=4.0.0,<5.0.0
    - robocorp-log >=3.0.0,<4.0.0
    - robocorp-workitems >=1.4.7,<2.0.0
    - robocorp-vault >=1.3.8,<2.0.0
    - robocorp-storage >=1.0.5,<2.0.0

test:
  imports:
    - robocorp
    - robocorp.tasks
    - robocorp.log
    - robocorp.workitems
    - robocorp.vault
    - robocorp.storage
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robocorp/robocorp/
  summary: Robocorp core libraries for Python automation
  description: This is a metapackage for installing the core libraries of Robocorp Python automation framework. The following packages are currently included robocorp-tasks robocorp-log robocorp-workitems robocorp-vault robocorp-storage
  doc_url: https://robocorp.com/docs/python/robocorp
  doc_source_url: https://github.com/robocorp/robo/tree/master/docs
  dev_url: https://github.com/robocorp/robo#libraries
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - zaigner
    - conda-forge/robocorp-tasks
    - conda-forge/robocorp-log
    - conda-forge/robocorp-workitems
    - conda-forge/robocorp-vault
    - conda-forge/robocorp-storage
